# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cSKyHHlxJqkHr7a4iwqN/OSZwalOSjDB8mog0fkMzISnll5+Y5/gBDs/2InX7z/dt44kVAVnhZ8xgKHI9CCrUkCiB7r4ixHVuKfbL/ltBi8lxDFIrXr6tgy7b0d753z7JquE+jMfgKtrQkLzsPE+e2TbeRuCEpXyEgRxZImp31akuy5vxyZL6MqNQyfnmA/RdRVYAiCo83DJwUBZdXm8pZsGoMaGHOh7iwsUTC+LsY+tThA7ffic+FtOn81E1a0gcF1P9cHpR+jIwCcdUrTTlQDobJR08Z5FlfLX0uWM2rfcA6JDDBuip67p6p8UpjPfQ5vAATw4KcIgdgUFQIeJnykLLoU3+OzengQZ0CaR9KtBRO/3T1y+1R/KVFVvKGZeuLpRHwtByhVNyCWCpPEqPTrXCN4LDVgS8rQSFIcp/GWfWO7C6t1aQ+rOzKfiQdhf+ZMbaU5a3Z7bEvSJQSYOPb3NGxXGKj3se1Z5ntjhW/T/m3FUo4P7Mqa5YNknpbPlp03nyo7p2lc99qWQ4mF9ESBH9yJi8HLxJ8uXEq9s7W/kZMydbY8zVX5UJqM6SBv77MDzs9dF3HnYEVNSeIPpJBZwF1s+MR180PoFsPjASZMvZY05whvmxUFL1UxF7qbkPewy/4otI8Tp0hWHEkCCVB0RsEbiIEYsQXGuGEBZPWM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
