travis:
  secure:
    BINSTAR_TOKEN: a+LpzsmfsfyUGelaL/MwXEbxPxwMcOvBXvySoXFuEraE6zGAq900hfMVY/YSxeEq1dAiJCy1+o4bgqDnV5IfRHyLZQYk1mOjQnxqA8u2VYvfx0HHsGY75rEiJeyWpDFl+6JmFzkGQrEjGBpYZxqx9iRJGFtYZeQOj6sFXoDFTbpU6huBgVCQCpxHdrk7fHBVDifPKAVVGEjPAEeOTWbHV1Mh9fwVX/VW6JJbW8YWKa5icfow3rG/zcmdJLKWv+aq8XmWFWV+fVF56TVCsE1KMpsZgLwlrid6VUYFPCVT28EqiCQ9+goHisRntTtEuBaCegzhdlclMxVAoqgH0srIVDEbDIQk8Lj1d6TuxSmMASWukhE8RQDsEDO62kBRgmd363+rU+g1eH22/aPwAm0q19KK55ukaVK1aRD7umkKVvcoQDMkaAT6pE+Aqcp7Pqb0Dp5ddYi77iYBjl6ZC4Ch5hMfL4o2LmD4j1qNIZugXKLxGAulSrEAoKQUgyCHX7+/j7AEselnIZK2BCF11OnZ6eJnAv9fb801M3t7OZZL1wK5wb5aRzAK4+3D/9lSltVQwtly15pHooPw8bHaTevBHh38DArXxChIWreXc+Q8UF5I3Q0nGIzAcXfev+5ihbTwxhKW4BG1FhzwwykKI0BOZGgJ0IVoDYWJByHb9A0+jUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
